[tool.poetry]
name = "trade-executor"
version = "0.1.0"
description = "Trading strategy execution and backtesting"
authors = ["Mikko Ohtamaa <mikko@tradingstrategy.ai>"]
homepage = "https://tradingstrategy.ai"
repository = "https://github.com/tradingstrategy-ai/trade-executor"
license = "APGL"
readme = "README.md"
keywords = ["algorithmic trading", "ethereum", "cryptocurrency", "uniswap", "quantitative finance", "binance", "blockchain", "pancakeswap", "polygon", "web3"]
packages = [
    { include = "tradeexecutor" },
]

[tool.poetry.dependencies]
# Scipy compatibility
# https://stackoverflow.com/questions/71764027/numpy-installation-fails-when-installing-through-poetry-on-m1-and-macos/71764028#71764028
python = ">=3.10,<3.11"

# Use these during development
# web3-ethereum-defi = {path = "deps/web3-ethereum-defi", develop = true}
# trading-strategy = {path = "deps/trading-strategy", develop = true}

# Locked for a release
web3-ethereum-defi = "^0.11"
trading-strategy = "^0.8.1"

typer = "^0.4.0"
colorama = "^0.4.4"
pyramid = "^2.0"
coloredlogs = "^15.0.1"
waitress = {version="^2.0.0", optional = true}
requests = "^2.27.1"
web3 = "^5.26.0"

# 3.20.2 broke on Mac
# See https://github.com/protocolbuffers/protobuf/issues/10571
# for discussion if still fails
protobuf = "^3.20.3"

# This is moved to optional dependencies as we want to get rid of this
trading-strategy-qstrader = {version="^0.5",  optional = true}
prompt-toolkit = "^3.0.31"
psutil = "^5.9.0"
discord-webhook = "^0.15.0"
WebTest = {version="^3.0.0", optional = true}
pyramid-openapi3 = {version="^0.13", optional = true}
python-logging-discord-handler = "^0.1.3"
APScheduler = "^3.9.1"
pandas-ta = "^0.3.14-beta.0"
python-logstash-tradingstrategy = "^0.5.0"
matplotlib = "^3.6.0"
notebook = "^6.4.12"
ipywidgets = "^8.0.2"

#
# This package is to be used in various environemnts
# - Execution oracles (makes trades)
# - Client side Python within a browser
#
[tool.poetry.extras]
qstrader = ["trading-strategy-qstrader"]

# These dependencies are not neededon the client side code
web-server = ["WebTest", "pyramid-openapi3", "waitress"]

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
ipdb = "^0.13.9"
flaky = "^3.7.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
trade-executor = 'tradeexecutor.cli.main:app'
get-latest-release = 'tradeexecutor.cli.latest_release:main'

[tool.pytest.ini_options]
addopts = "-s --tb=native"
testpaths = [
    "tests",
]
