[tool.poetry]
name = "trade-executor"
version = "0.1.0"
description = "Trade executor for algorithmic trading on decentralised exchanges"
authors = ["Mikko Ohtamaa <mikko@tradingstrategy.ai>"]
license = "APGL"
packages = [
    { include = "trade-executor" },
]

[tool.poetry.dependencies]
python = "^3.9"
web3-ethereum-defi = {path = "../web3-ethereum-defi", develop = true}
trading-strategy = {path = "../trading-strategy", develop = true}
typer = "^0.4.0"
colorama = "^0.4.4"
pyramid = "^2.0"
coloredlogs = "^15.0.1"
waitress = "^2.0.0"
requests = "^2.27.1"
web3 = "^5.26.0"
trading-strategy-qstrader = "^0.5"
prompt-toolkit = "^3.0.28"
psutil = "^5.9.0"
discord-webhook = "^0.15.0"
WebTest = "^3.0.0"
pyramid-openapi3 = "^0.13"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
ipdb = "^0.13.9"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
trade-executor = 'tradeexecutor.cli.main:app'
