[tool.poetry]
name = "tradeexecutor"
version = "0.1.0"
description = "Oracle algorithm executor and P2P"
authors = ["Mikko Ohtamaa <mikko@opensourcehacker.com>"]
license = "APGL"

[tool.poetry.dependencies]
python = "^3.9"
tradingstrategy = "^0.4.0"
typer = "^0.4.0"
colorama = "^0.4.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
trade-executor = 'tradeexecutor.cli.main:app'